// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_500.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/blog.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/send.tsx";
import * as $7 from "./routes/siren.tsx";
import * as $$0 from "./islands/color-mode.tsx";
import * as $$1 from "./islands/language.tsx";
import * as $$2 from "./islands/mobile-header.tsx";
import * as $$3 from "./islands/project.tsx";

const manifest = {
  routes: {
    "./routes/_500.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/blog.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/send.tsx": $6,
    "./routes/siren.tsx": $7,
  },
  islands: {
    "./islands/color-mode.tsx": $$0,
    "./islands/language.tsx": $$1,
    "./islands/mobile-header.tsx": $$2,
    "./islands/project.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
